version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules # Exclude node_modules from host bind mount
    environment:
      NODE_ENV: development
      PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MONGO_URI: mongodb://mongo:27017/naijatalentrank # Connect to the mongo service
    depends_on:
      - mongo
      - redis

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile # Will create this Dockerfile later
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/apps/web/node_modules # Exclude node_modules from host bind mount
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: http://api:3001/api # Connect to the api service
    depends_on:
      - api

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo_data:
